[[bin]]
name = "p1"

[[bin]]
name = "p2"

[package]
name = "d01"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.12.2"
color-eyre = "0.6"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
