[[bin]]
name = "d01p1"
path = "src/bin/p1.rs"

[[bin]]
name = "d01p2"
path = "src/bin/p2.rs"

[package]
name = "d01"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.12.2"
color-eyre = "0.6"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
aoc_runner = { path = "../aoc_runner" }
